apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    tier: redis-sentinel
    role: sentinel
    redis-sentinel: "true"
spec:
  selector:
    app: redis
    tier: redis-sentinel
  ports:
  - name: sentinel
    protocol: TCP
    port: 26379
    targetPort: 26379
  type: ClusterIP
