apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    tier: redis
    role: redis
spec:
  selector:
    app: redis
    tier: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
